name: cuicatl_mplayer
description: Reproductor de mÃºsica Cuicatl Ultimate.
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Iconos estilo iOS
  cupertino_icons: ^1.0.6
  
  # Fuentes modernas (Outfit)
  google_fonts: ^6.1.0
  
  # Motor de Audio Profesional
  just_audio: ^0.9.36
  
  # Base de datos de canciones y metadatos
  on_audio_query: ^2.9.0
  
  # Manejo de Permisos de Android
  permission_handler: ^11.2.0
  
  # Guardar Favoritos y Nombre
  shared_preferences: ^2.2.2
  
  # NUEVO: Extraer colores vibrantes de la imagen
  palette_generator: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
