name: cuicatl_mplayer
description: Reproductor de mÃºsica Cuicatl Pro.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Iconos y UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  # Audio
  just_audio: ^0.9.36
  on_audio_query: ^2.9.0
  # Permisos y Sistema
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2 # Para guardar el nombre
  # Efectos Visuales
  ui: 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
