name: cuicatl_mplayer
description: Reproductor de música Cuicatl.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Reproducción de audio
  just_audio: ^0.9.36
  # Lectura de archivos y carátulas
  on_audio_query: ^2.9.0
  # Permisos
  permission_handler: ^11.2.0
  # UI
  google_fonts: ^6.1.0
  palette_generator: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
