name: cuicatl_mplayer
description: Reproductor de música Cuicatl Ultimate.
publish_to: 'none'
version: 8.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Iconos y Fuentes
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Audio y Notificaciones
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  
  # Datos y Permisos
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  
  # Detectar versión de Android (Vital para Android 13/14)
  device_info_plus: ^10.1.0
  
  # UI y Colores
  palette_generator: ^0.3.3
  android_intent_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
